# Generated by Django 5.0.6 on 2024-06-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
