# Generated by Django 5.0.6 on 2024-06-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_remove_artist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vinyl',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinyls', to='hub.artist'),
        ),
    ]
