# Generated by Django 5.0.6 on 2024-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_remove_vinyl_author_remove_vinyl_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
