# Generated by Django 5.0.6 on 2024-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_vinyl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
