# Generated by Django 5.0.6 on 2024-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_alter_vinyl_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='dominantcolor',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
