# Generated by Django 5.0.6 on 2024-07-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
