# Generated by Django 5.0.6 on 2024-07-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
