# Generated by Django 5.0.6 on 2024-07-14 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_remove_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='artist',
            field=models.ForeignKey(help_text='Select the artist of the vinyl', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinyls', to='hub.artist'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='dominantcolor',
            field=models.CharField(help_text='Dominant color of the vinyl', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='genre',
            field=models.CharField(help_text='Enter the genre of the vinyl', max_length=50),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='image',
            field=models.ImageField(help_text='Upload image of the vinyl', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price of the vinyl', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='slug',
            field=models.SlugField(help_text='Unique slug for the vinyl URL', unique=True),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='stock',
            field=models.PositiveIntegerField(help_text='Enter the stock quantity of the vinyl'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='tags',
            field=models.ManyToManyField(help_text='Select tags for the vinyl', to='hub.tag'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='title',
            field=models.CharField(help_text='Enter the title of the vinyl', max_length=50),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='year',
            field=models.IntegerField(help_text='Enter the release year of the vinyl', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
