# Generated by Django 5.0.6 on 2024-07-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_alter_rating_rating_alter_rating_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
